kind: pipeline
type: kubernetes
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: deploy hugo
  image: twofirstnames/drone-ansible
  settings:
    playbook: ansible/main.yml
    inventory: ansible/inventory
    private_key:
      from_secret: private_key
    vault_password:
      from_secret: vault_password