kind: pipeline
name: default

steps:
- name: clone infra
  image: alpine/git
  commands:
  - git clone https://git.twofirstnames.org/joe/infra.git
- name: deploy hugo
  image: plugins/ansible:3
  settings:
    playbook: infra/ansible/hugo.yml
    inventory: infra/ansible/inventory
    private_key:
      from_secret: private_key
    vault_password:
      from_secret: vault_password